version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "nikhilbadyal"
    labels:
      - "dependencies📌"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - "nikhilbadyal"
    labels:
      - "dependencies📌"
