name: 'Telegram GitHub Action'
description: 'A GitHub action to interact with telegram'
author: 'nikhilbadyal'
inputs:
  github_token:
    required: true
    description: 'Github token'
  release_pattern:
    required: true
    description: 'Github token'


runs:
  using: 'node16'
  main: 'dist/index.js'
