name: Run tests

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
  pull_request:
    branches:
      - 'main'
      - 'releases/v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Validate
        uses: docker/bake-action@v2
        with:
          targets: validate
      -
        name: Test
        uses: docker/bake-action@v2
        with:
          targets: test
        env:
          github_token: ${{ secrets.GH_TOKEN }}
          release_pattern: '0.0.1*'
      -
        name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/clover.xml
